### ISSUE TITLE
Cannot Import to v2017.2.5

### ISSUE THREAD

**Issue by aelfric** [oizo/intellij-colorblind-scheme#1]
Hi,

I am also a color blind dev working primarily in Java and a newcomer to Intellij.  I like your theme from the screenshots.  When I try to import this in v2017.2.5 it tells me the `icls` file does not contain any settings.  Do you know what I'd need to do to import this into this version of Intellij?

**Comment by hw4m** [comment]
Hey, I'll have a look at it as soon as i have time, and get back to you.

**Comment by hw4m** [comment]
Oh, if you want to import the settings, then you'll need to import the `ColorBlind.jar`. To use the `ColorBlind.icls` file you'll have to copy/paste it into your `/path/to/IntelliJ-settings/colors` folder, and then in IntelliJ select the scheme from Settings->Editor->Colors & Fonts
