### ISSUE TITLE
Missing .jar file

### ISSUE THREAD

**Issue by lucaspal** [oizo/intellij-colorblind-scheme#2]
Hi, I would like to try this color scheme (it looks great at least for my eyes :P ) and I would like doing that by importing the .jar file. 
I cannot find it though, am I missing something or it is simply not there?

**Comment by hw4m** [comment]
Hi, sorry for the late answer. No I du not currently include the .jar file, as I found it difficult to remember to update both the .icls and the .jar - though it seems so simple, yet i failed when trying. Also with the icls it allows me to see the changes line by line, and others to see exactly what they get. Perhaps I'll include i the jar again if it's something that will benefit you and others.

**Comment by lucaspal** [comment]
That's fair enough, it gives more transparency as bonus point. 
In this case the installation instructions about the jar files should be removed.

Just created a PR for this: #https://github.com/oizo/intellij-colorblind-scheme/pull/3
